website:
  port: 3000
  secret: ""
  secure: false
  theme: default
  logger: false
  arcio_id: ""

discord:
  id: ""
  secret:
  callback: http://localhost:3000/auth/callback
  prompt: false
  token:
  guild_id: ""
  invite: https://discord.gg/kTw8x4CH9c

pterodactyl:
  domain:
  key:

database:
  connection_uri: mongodb+srv:// # your SRV URI
  name: dashactyl

api:
  keys:
    - d3f4uLt # whitelisted Dashactyl API keys
  
  users: true
  coins: true
  coupons: true
  plans: true
  resources: true
  j4r: true

afk:
  coins_per_minute: 10
  # domain_lock: localhost:8000

renewal:
  renewal_time: 6.048e+8
  deletion_time: 8.64e+7
  renew_fee: 10
